- name: Frontend playbook
  hosts: all
  become: yes
  tasks:
  - name: Disable default nginx module
    ansible.builtin.shell: dnf module disable nginx -y

  - name: Enable Nginx 24 Version
    ansible.builtin.shell: dnf module enable nginx:1.24 -y

  -  name: Install Nginx
     ansible.builtin.dnf:
      name: nginx
      state: latest

  -   name: Copy nginx config file
      ansible.builtin.template:
       src: nginx.conf
       dest: /etc/nginx/nginx.conf


  - name: Start Nginx Service
    ansible.builtin.systemd_service:
     state: restarted
     name: nginx
     enabled: true
