- name: Demo on template
  hosts: localhost
  tasks:
    - name: COpy file
      ansible.builtin.copy:
        src: hello.txt
        dest: /tmp/h1.txt

    - name: Template file
      ansible.builtin.template:
        src: hello.txt
        dest: /tmp/h2.txt

