- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Disbale redis default
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis 7
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install Redis 7
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis config file - Update Protect Mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes
