- name: Filters demo
  hosts: localhost
  connection: local
  vars:
    x: 1,2,3
  tasks:
    - name: print the second value of x
      ansible.builtin.debug:
        msg: "{{ split[1] }}"
      vars:
        split: "{{x | split(',') }}"